In [2]:
import numpy as np
np.array([[1,2,3],[4,5,6]])
np.arange(0,9)
np.arange(9)
np.linspace(1,6,5)
np.zeros((4,2))
np.ones((2,3))
np.full((2,2),3)
np.empty((2,2))
np.repeat([1,2,3],3)
np.random.randint(1,100,5)
x = np.arange(0,10)
x.reshape(5,2)
x = np.arange(0,12).reshape(2,3,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [3]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [6]:
a = np.array([0,1,2])
a[0]=4
a

array([4, 1, 2])

In [10]:
x = np.array([[1,2],[3,4]])
y = np.array([[6,7,8],[9,10,11]])
z = np.append(x,y)
z

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [14]:
x = np.array([[1,2],[3,4]])
y = np.array([[6,7],[9,10]])
z = np.concatenate((x,y),axis=1)
z

array([[ 1,  2,  6,  7],
       [ 3,  4,  9, 10]])

In [15]:
x = np.array([[1,2],[3,4]])
y = np.array([[6,7],[8,9],[10,11]])
alfa = np.vstack((x,y))
alfa

array([[ 1,  2],
       [ 3,  4],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
x = np.array([[1,2],[3,4]])
y = np.array([[6,7,8],[9,10,11]])
beta = np.hstack((x,y))
beta

array([[ 1,  2,  6,  7,  8],
       [ 3,  4,  9, 10, 11]])

In [18]:
x = np.arange(0,12).reshape(2,6)
y = np.arange(5,17).reshape(2,6)
print(x)
print(y)
z = x * y
z

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 5  6  7  8  9 10]
 [11 12 13 14 15 16]]


array([[  0,   6,  14,  24,  36,  50],
       [ 66,  84, 104, 126, 150, 176]])

In [21]:
x = np.arange(0,10).reshape(5,2)
y = np.transpose(x)
y

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])